#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
#include <string.h>
#define int long long
// some note:
// usually, arbitrary grammar can be converted to a backtrack-free Top-down parsing -- section 3.3.1
// catagories of Top-down parsers: 
//(1) top-down recursive-descent parser .    It is hand-coded
//(2) top-down table-driven LL(1) parser.    It is generated by computer

// backtrack-free grammar == predictive grammar
//TO DO: io-file

char *src;  // pointer to source code string;
int line, col;             // count how many lines&columns have been parsed
int poolsize;         // default size of text/data/stack

int tokenchar;            // current tokenchar
int token;
int calculatorOutput[128];
char isNum[128];
int nextEmpty = 0;

int * idmain; // the 'main' function  -------(3)

// these three variables are used in next()
int token_val;  // used in next()-recognizing number
int *current_id,// used in next()-recognizing identifier. 
    *symbols;   // symble table.used in next()-recognizing identifier. 

// ----------fields of the identifier library
enum {IdOrKey, Hash, Name, SizeOfId, Type, Class, Value, BType, BClass, BValue, IdSize};//attributes of the symbol table(except for the last one -- IdSize)
// each identifier takes up in total 9 cells of the table (Token ~ BValue)

// ----------types of tokens (operators last and in precedence order)
enum {
  Num = 128, UINT, CHAR, STRING, Ident,
  Int, Char, Struct, Void, 
  If, Else, While, For, Break, New, Delete, Return, Extern, 
  Lor, Lan, Eq, Ne, Le, Ge, Shl, Shr, Inc, Dec}; 
// Some charactors, such as "[" and "~", are not included because they themselves can be a token.
// the reason why we do not assign special tokens for "[" and "~" are:
// 1. the are single-character, not like "=="
// 2. they do nothing with precedence

int maxOne(int a, int b)
{
    if (a >= b)
        {return a;}
    else
    {
        {return b;}
    }
    
}
 
void next() 
{    // when will it "return"? answer: when "while" ends. then, when will the "while" end? answer: (1)it recognizes sth (2)*src == 0, i.e. the end of the article
     // the business about "forced exit because of unknown charactor" is done by GrammarPaser   
	char *last_pos; //  src is the start pointer of the malloc(). i don't think it is good to let src change such as "src++;
    int hash;

    while (tokenchar = *src)  // this while-loop is used to 1. skep whitespaces 2. report lexing error -- unknown character
    {
        ++col;
		++src;
        // parse token here
        if (tokenchar == '\n')  //------------------------- a new line will start
        {
            ++line;
            col = 0;
        }
        else if ( (tokenchar == 0x09) || (tokenchar == 0x20) || (tokenchar == 0xD) )  // ---------- whitespace
        {
            ;
        }
        else if (tokenchar == '#')
        {
            // skip macro, because we will not support it
            while (*src != 0 && *src != '\n') 
            {
                src++;
            }
        }    
        else if (tokenchar == '/') 
        {
            if (*src == '/') // --------------------------------------  single line comment
            {           
                while (*src != 0 && *src != '\n') 
                {
                    ++src;
                }
            } 
            else if (*src == '*')// --------------------------------------  multiline comment
            {
            	char endMultiComment = 0;
            	src++;
				while ((*src != 0)   &&  (endMultiComment == 0)) 
                {
                    if (*src == '*')
                    {
                    	src++;
                    	if (*src == '/')
                    	{
                    		endMultiComment = 1;
						}
					}
					src++;
                }
			}
			else // --------------------------------------------- divide operator
            {           
                //tokenchar = Div;
                token = '/';
                return;
            }
        }
		else if (  (tokenchar >='a'&& tokenchar<='z')  ||  (tokenchar >= 'A' && tokenchar <= 'Z')  ||  (tokenchar == '_')  )  
        { // --------------identifiers or identifiers->keywords
            last_pos = src - 1; // the address of the first char of the identifier
            hash = tokenchar;  

            while ((*src >= 'a' && *src <= 'z') || (*src >= 'A' && *src <= 'Z') || (*src >= '0' && *src <= '9') || (*src == '_')) 
            {
                //hash = hash * 147 + *src; // each different identifier represents a different value, "hash" ; 
                // '0'=48  '9'=57 'A'=65 'Z'=90 '_'=95 'a'=97 'z'=122
                // No!!!! hash only support the identifier whose size is <=9. Otherwise, the hash value will saturate :-(
                src++;
            }

            // look for existing identifier, i.e. linear search 
            current_id = symbols;  // record the information of each identifier into the library:int * symbols
            while (current_id[IdOrKey])// if current_id[IdOrKey] == 0 then the identifier is a new comer
            {
                if (   !memcmp((char *)current_id[Name], last_pos, maxOne(current_id[SizeOfId], src - last_pos))   )
                // int memcmp (const void *s1, const void *s2, size_t n) is used to compare the top n characters of the memories pointed by s1 and s2
                // maxOne() is used to solve this circumstance: the old existing Ident is "abcde", and the new one is "abc"
                {
                    token = current_id[IdOrKey];
                    return;
                }
                current_id = current_id + IdSize;
            }

            // store new ID
            token = current_id[IdOrKey] = Ident;          
            current_id[Name] = (int)last_pos;  // stores the position of the first char of the identifier
            current_id[SizeOfId] = src - last_pos;// store how many character this identifier has
            return;

        }   
        else if (tokenchar >= '0' && tokenchar <= '9')   // ------------------------------number dec(123) hex(0x123) oct(017) // WHAT IF "1234ZABC": it is the same as "1234 ZABC"
        {

            if (tokenchar > '0')   // DEC, starts with [1-9]
            {
                token_val = tokenchar - '0';
                while (*src >= '0' && *src <= '9') 
                {
                    token_val = token_val*10 + *src++ - '0';
                }
            } 
            else 
            {
                if (*src == 'x' || *src == 'X')   //HEX
                { 
                    ++src;
                    int current_SlgDigit= 0;
                    token_val = 0;
                    while ((*src >= '0' && *src <= '9') || (*src >= 'A' && *src <= 'F') || (*src >= 'a' && *src <= 'f')) 
                    {
                        if (*src >= 'A' && *src <= 'F') 
                        {
                            current_SlgDigit = *src - 'A' + 10;
                        }
                        else if (*src >= 'a' && *src <= 'f')
                        {
                            current_SlgDigit = *src - 'a' + 10;
                        }
                        else
                        {
                            current_SlgDigit = *src - '0';
                        }

                        token_val = token_val*16 + current_SlgDigit;
                        ++src;
                    }
                    
                } 
                else    // OCT
                {
                    token_val = 0;
                    while (*src >= '0' && *src <= '7') 
                    {
                        token_val = token_val*8 + *src++ - '0';
                    }
                }
            }

            //tokenchar = Num;
            token = Num;// output of next()
            return;
        }
        else if (tokenchar == '\'') // ---------- single char
        {
            token = CHAR;
            token_val = *src++;
            if (*src == '\'')
            {       
                src++;
            }
            else
            {
                printf("lexing error: \' should appear at (line %d, col %d) but not", line, col);
                exit(-1);
            }
            
        }
        else if (tokenchar == '+') 
        {
            // parse '+' and '++'// ------------------------------------
            if (*src == '+') 
            {
                src ++;
                token = Inc;
            } 
            else 
            {
                token = '+';
            }
            return;
        }
        else if (tokenchar == '-') 
        {
            // parse '-' and '--'// ------------------------------------
            if (*src == '-') 
            {
                src ++;
                token = Dec;
            } 
            else 
            {
                token = '-';
            }
            return;
        }
		 else if (tokenchar == '*') 
        {
            token = '*';
            return;
        }
		
        else if (tokenchar == '=') // --------------------------------------------- = + - * & && | || != > >= < <=
        {
            // parse '==' and '='-------------------------------------------
            if (*src == '=') 
            {
                src ++;
                token = Eq;
            } 
            else 
            {
                token = '=';
            }
            return;
        }
        
        else if (tokenchar == '!') 
        {
            // parse '!='// ------------------------------------
            if (*src == '=') 
            {
                src++;
                token = Ne;
            }
            return;
        }
        else if (tokenchar == '<') 
        {
            // parse '<=', '<<' or '<'// ------------------------------------
            if (*src == '=') 
            {
                src ++;
                token = Le;
            } 
            else if (*src == '<')
            {
                src ++;
                token = Shl;
            } 
            else 
            {
                token = '<';
            }
            return;
        }
        else if (tokenchar == '>') // ------------------------------------
        {
            // parse '>=', '>>' or '>'
            if (*src == '=') 
            {
                src ++;
                token = Ge;
            } 
            else if (*src == '>') 
            {
                src ++;
                token = Shr;
            } 
            else 
            {
                token = '>';
            }
            return;
        }
        else if (tokenchar == '|') // ------------------------------------
        {
            // parse '||' or '|'
            if (*src == '|') 
            {
                src ++;
                token = Lor;
            } 
            else 
            {
                token = '|';
            }
            return;
        }
        else if (tokenchar == '&') // ------------------------------------
        {
            // parse '&&' and '&'
            if (*src == '&') 
            {
                src ++;
                token = Lan;
            } 
            else 
            {
                token = '&';
            }
            return;
        }  
        else if (tokenchar == '~' || tokenchar == ';' || tokenchar == '{' || tokenchar == '}' || tokenchar == '[' || tokenchar == ']' || tokenchar == '(' || tokenchar == ')' || tokenchar == ']' || tokenchar == ',' || tokenchar == ':' || tokenchar == '?' || tokenchar == '%') 
        {
            // directly return the character as token;
            token = tokenchar;
            return;
        }
        else
        {
            printf("lexing error: unknown character in (line %d, col %d)", line, col);
            exit(-1);
        }
        

    }
    
    return;
}

void recordToken()
{
    if (token == Num)
    {
        calculatorOutput[nextEmpty] = token_val;
        isNum[nextEmpty] = 1;
    }
    else
    {
        calculatorOutput[nextEmpty] = token;
        isNum[nextEmpty] = 0;  
    }
    nextEmpty++;
}


void addMem2record(int insert, int tokenInsert, char isNumInsert)
{
    int i=0;
	for (i=nextEmpty; i>insert; i--)
    {
        calculatorOutput[i] = calculatorOutput[i-1];
        isNum[i] = isNum[i-1];
    }
    calculatorOutput[insert] = tokenInsert;
    isNum[insert] = isNumInsert;
    nextEmpty++;
}

void match(int expectedChar)
{
	if (token != expectedChar)
	{
		printf("------error in (line %d, col %d): --------\n", line, col);
		printf("expected tokenchar: %c(%d), but got: %c(%d)\n", expectedChar, expectedChar, tokenchar,tokenchar);
		exit(-1); // main()is forced to stop
	}
	
	next();

}

struct multiOutput
{
    int value;
    int location;
};


int expr();

struct multiOutput factor()
{
    struct multiOutput factorOut;
    factorOut.location = nextEmpty;
  
	if (token == '(')
	{
		//recordToken();
        match('(');        
		factorOut.value = expr();
        
        //recordToken();
		match(')');        
	}
	else
	{
		factorOut.value = token_val;      
		recordToken();
        match(Num); // see if the tokenchar is a number, if not, the main() will be forced to exit        
	}
	return factorOut;
}


int term_doMulDiv(int longValue, int leftBracket)
{
	struct multiOutput factorOut;

    if (token == '*')
	{
		recordToken();
        match('*');               
		factorOut= factor();
        longValue = longValue * factorOut.value;
        // add ( at leftBracket
        addMem2record(leftBracket, '(', 0);
        // add ) at end
        addMem2record(nextEmpty, ')', 0);// first add ) then take the tail )

		return term_doMulDiv(longValue, leftBracket);
	}
	else if (token == '/')
	{
        recordToken();
		match('/'); 
        factorOut= factor();
        longValue = longValue / factorOut.value;      

        // add ( at leftBracket
        addMem2record(leftBracket, '(', 0);
        // add ) at end
        addMem2record(nextEmpty, ')', 0);

		return term_doMulDiv(longValue, leftBracket);
	}
	else
	{
		return longValue;	
	}
}


struct multiOutput term()
{
	struct multiOutput factorOut = factor();
    struct multiOutput termOut;
    termOut.value = term_doMulDiv(factorOut.value, factorOut.location);
	termOut.location = factorOut.location;
    return termOut;
}


int expr_doAddSub(int longValue, int leftBracket)
{
	struct multiOutput termOut;
    if (token == '+')
	{
		recordToken();
        match('+');
        termOut = term();        
		longValue = longValue + termOut.value;
        // add ( before leftBracket
        addMem2record(leftBracket, '(', 0);
        // add ) before nextEmpty
        addMem2record(nextEmpty, ')', 0);

		return expr_doAddSub(longValue, leftBracket);
	}
	else if (token == '-')
	{
        recordToken();
		match('-');
        termOut = term();         
		longValue = longValue - termOut.value;
        // add ( before leftBracket
        addMem2record(leftBracket, '(', 0);
        // add ) before nextEmpty
        addMem2record(nextEmpty, ')', 0);

		return expr_doAddSub(longValue, leftBracket);
	}
	else
	{
		return longValue;
	}
}

int expr()
{
    struct multiOutput termOut = term();
	return expr_doAddSub(termOut.value, termOut.location);
}

//HERE HERE check if all {} and [] are implemented

void ty() // has error report; does next() 
{
    if (  (token == Void) || (token == Int) || (token == Char) || (token == Ident)  )
    {
        next();
        if (token == '*') 
        {
            //record
            next();
        }
    }
    else
    {
        printf("parser error") ;
        exit(-1) ;
    }
}

void params() 
{
    if (  (token == Void) || (token == Int) || (token == Char) || (token == Ident)  ) 
    {
        ty();
        match(Ident) ;
        while (token == ',') 
        {
            match(',');
            ty() ;
            match(Ident);
        }
    }// else do nothing
}


void lvalue()
{

}


void assignSuffix()
{
    if (token == '=')
    {
        next();
        expr();
    }
    else if (token == Inc)
    {
        next();
    }
    else
    {
        match(Dec);
    }
    
}


void varassign()
{
    if (token == Ident)
    {
        next();
        if (token == '*')
        {
            next();
        }

        if (token == Ident)
        {
            next();
            match('=');
            expr();
        }
        else if (token == '(') // assign sth by running a function
        {
            next();
            if (token != ')')
            {
                expr();
                while (token == ',')
                {
                    next();
                    expr();
                }
            }
            match(')');
        }
        else if (token == '[') // assign array
        {
            next();
            expr();
            match(']');
            if (token == '.')
            {
                next();
                match(Ident);
            }
            assignSuffix();
        }
        else // assign identifier
        {
            assignSuffix();
        }
        
    }
    else
    {
        ty();// local variable initialization
        match(Ident);
        match('=');
        expr();
    }
    
}


void stmtElseSuffix()
{
    if (token == Else)
    {
        next();
        stmt();
    }// else do nothing
}
void stmt() 
{
    if (token == '{')
    {
        next();
        while (token ! = '}') 
        {
            stmt () ;
        }
        match('}');    
    }
    else if (token == If)
    {
        next();
        match('(');
        expr();
        match(')');
        stmt();
        stmtElseSuffix();
    }
    else if (token == While)
    {
        next();
        match('(');
        expr();
        match(')');
        stmt();
    }
    else if (token == Break)
    {
        next();
        match(';');
    }
    else if (token == Return)
    {
        next();
        if (token != ';')
            {expr();}
        match(';');
    }
    else if (token == Delete)
    {
        next();
        match('[');
        match(']');
        match(Ident);
        match(';');
    }
    else if (token == For)
    {
        next();
        match('(');
        varassign();
        match(';');
        expr();
        match(';');
        assign();
        match(')');
        stmt();
    }
    else
    {
        varassign();
        match(';');
    }
    

}


void globalSuffix2 () 
{
    if (token == '(') 
    {
        next() ;
        params() ;
        match(') ') ;
        match(';') ;
    }
    else
    {
        match(';') ;
    }
}

void globalSuffix1() 
{
    if (token == '(') 
    {
        next() ;
        params() ;
        match(') ') ;
        match('{') ;
        while (token ! = '}') 
        {
            stmt () ;//if stmt() eats an unknown token, it will report error
        }
        match('}') ;

    }
    else if (token == '=') 
    {
        expr () ;
        match(';') ;
    }

}


void global() 
{
    if (token == Extern) 
    {
        match(Extern) ;
        ty() ;
        match(Ident) ;
        globalSuffix2() ;
    }//HERE HERE why does the original program use 2 char enum?
    else if (  (token == Void) || (token == Int) || (token == Char) || (token == Ident)  ) 
    {
        ty() ;
        match(Ident)； 
        globalSuffix1();
    }
    else
    {
        match(Struct) ;
        match(Ident) ;
        match('{') ;
        while (  (token == Void) || (token == Int) || (token == Char) || (token == Ident)  )  // 首选开头匹配，如果是nonterminal 才选结尾不匹配
        {
            ty() ;
            match('Ident') ;
            match(';') ;
        }
        match('}') ;
        match(';') ;
    }

}

void program() 
{
    next() ;//initialize tokenchar
    while (token > 0) //to avoid conflict against ascii, enum should start from 128
    {
        global () ;
    }
}

void program() 
{
    next();                  // get next tokenchar
    while (tokenchar > 0)
    {    
        int caculatorR = expr();
        
		int i=0;
        for (i=0; i<nextEmpty; i++)
        {
            if (isNum[i] == 1)
            {
                printf("%d", calculatorOutput[i]);
            }
            else
            {              
                printf(" %c ", calculatorOutput[i]);                              
            }          
        }
        printf("\n= %d", caculatorR);
        // the calculator do not have to consider EOF, the "while-loop" will 
    }

}



int main()
{
    int i;

    poolsize = 256 * 1024; // arbitrary size, set the size of 
    line = 1;
    col = 0;



// ---------add keywords to symbol table
    if (!(symbols = malloc(poolsize))) // save identifiers and keywords. the pointer, "current_id", slides itself to represent a certain identifier/keyword
    {
        printf("could not malloc(%d) for symbol table\n", poolsize);
        return -1;
    }
      memset(symbols, 0, poolsize);
    //current_id = symbols;no need to initialize the current_id here. next() will do this job

    src = " Int Char Struct Void If Else While For Break New Delete Return Extern main";
    i = Int;
    while (i <= Extern) // we are now in the main-function, the symbol table is still empty.
    {
        next(); // src will point to a "white space" when next() returns
        // thanks to the "while loop", when *src== white space, next() will continue rather than return
        current_id[IdOrKey] = i++; // for common identifiers, current_id[Token] = Id, while for key words, current_id[Token] = KeyWord
    }
    next(); idmain = current_id; // ??????????
    // when next() is running, current_id will traverse itself until point to a new black space.
    // the following space will be used for identifiers running in user's functions. // keep track of main 



// ----------start to read source code
    FILE * fp = NULL;
    char * filepath = "./files/test.txt";

    if (  (fp = fopen(filepath, "r")  ) == NULL) 
    {
        printf("could not open(%s)\n", filepath);
        return -1;
    }

    
    if (!(src = malloc(poolsize))) 
    {
        printf("could not malloc(%d) for source area\n", poolsize);
        return -1;
    }
    
    if (  (i = fread(src, sizeof(char), poolsize-1, fp)) <= 0) 
    { 
        printf("read() returned %d\n", i);
        return -1;
    }
    src[i] = 0; // add EOF character
    close(fp);

    line = 1;
    col = 0;
    program();   
    return 0;
}
